### ISSUE TITLE
macOS build instructions not included in readme..

### ISSUE THREAD

**Issue by iancd** [maleemjaved/epub-optimizer#1]
Hello Javed, 
Thanks for sharing epub-optimizer on github. 

Today I used the software on macOS to compress an epub and I'm very grateful. You may add these commands to your readme file for users on macOS. I tested and it worked great.

**Note: Requires Brew installed from https://brew.sh**
```
brew install python3 pngquant mozjpeg
pip3 install pathlib
mkdir ~/dev/
git clone https://github.com/maleemjaved/epub-optimizer.git ~/dev/
cd ~/dev/epub-optimizer
ln -f /usr/local/bin/pngquant ./thirdparty/pngquant.exe
ln -f /usr/local/bin/cjpeg ./thirdparty/cjpeg.exe
python3 main.py -f "path_to_epub_file"
```
Regards
Ian

**Comment by maleemjaved** [comment]
Hello Ian,
Thanks for using this utility and suggesting improvement in it, i have updated the **readme** file with macOS usage instructions as provided by you.

Regards: 
Aleem
